name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Python Path and Working Directory
        run: |
          cd /home/runner/work/Basic-CI-CD-Pipeline/Basic-CI-CD-Pipeline
          export PYTHONPATH=${PYTHONPATH}:.

      - name: Test Manual Import
        run: |
          source venv/bin/activate
          python -c "from app import app"
        

      - name: Run Tests
        run: |
          source venv/bin/activate
          pip list  # Lists installed Python packages
          ls -la
          pip install pytest pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html 
          echo "Tests passed"
