name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flask pytest coverage

      - name: Set Python Path and Working Directory
        run: |
          export PYTHONPATH=${PYTHONPATH}:./Basic-CI-CD-Pipeline
          cd /home/runner/work/Basic-CI-CD-Pipeline/Basic-CI-CD-Pipeline
          ls -la

      - name: Run Tests
        run: |
          source venv/bin/activate
          cd /home/runner/work/Basic-CI-CD-Pipeline/Basic-CI-CD-Pipeline
          pytest tests/test_app.py 
          echo "Tests passed"
