name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flask pytest coverage

      - name: Set Python Path
        run: export PYTHONPATH=${PYTHONPATH}:/home/runner/work/Basic-CI-CD-Pipeline

      - name: Run Tests
        run: |
          source venv/bin/activate
          coverage run -m pytest 
          coverage report
          echo "Tests passed"
