name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
    
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Python Path and Working Directory
        run: |
          cd /home/runner/work/Basic-CI-CD-Pipeline/Basic-CI-CD-Pipeline
          export PYTHONPATH=${PYTHONPATH}:.     

      - name: Run Tests
        run: |
          source venv/bin/activate
          pip list  # Lists installed Python packages
          pip install pytest pytest-cov
          pytest tests/test_app.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html  
          echo "Tests passed"
